
spring:
  profiles:
    active: dev2


---
spring:
  application:
    ###当前服务名
    name: wwywhdgg-eureka
  profiles: dev

server:
  ##端口号
  port: 8001
eureka:
  instance:
    hostname: wwywhdgg-peer1
    preferIpAddress: true
---
spring:
  profiles: dev1
  application:
    name: wwywhdgg-eureka2
server:
  port: 8002
eureka:
  instance:
    hostname: wwywhdgg-peer2
    preferIpAddress: true

---
spring:
  profiles: dev2
  application:
    name: ewwywhdgg-eureka3
server:
  port: 8003
eureka:
  instance:
    hostname: wwywhdgg-peer3
    preferIpAddress: true

---
eureka:
  instance:
    hostname: dev
  client:
    ##检索服务
    fetch-registry: false
    ##是否将自己注册到eureka
    register-with-eureka: false
    ##客户端默认去这个地址找注册中心
    service-url:
      ##zone 可以设置时区
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/,http://localhost:8003/eureka/
  server:
    ### 当eureka启动时，不能从集群节点中获取到instance注册信息，应该等多久
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    ###eureka多长时间更新一次数据
    peer-eureka-nodes-update-interval-ms: 100000
logging:
  level:
    org.springframework.cloud: debug